spring:
  application:
    name: proxyportal

npm:
  base-url: https://npm.klore.net
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkiLCJhdHRycyI6eyJpZCI6MX0sInNjb3BlIjpbInVzZXIiXSwiZXhwaXJlc0luIjoiMWQiLCJqdGkiOiJMcTl2ekhyYlErMVhOYzJOIiwiaWF0IjoxNzY2MTM1NDQ4LCJleHAiOjE3NjYyMjE4NDh9.gceQAool1T0s5jajT9uvB3eZt3OckNPxBJwY4kYNVObjb0Xqqguyj__EGHYRQD3nVObFJCl96CKZbZPnQf4Zt1CobmwEejfbv3BmeBg1CoVwxubCMeLrW144Z9VXYnsuzHbA1Z4vh2Qc_y7Sa9JH_I8bA5XD92McX7oyuEmAQ2sHVEid9sQmKN1bcdkKpBWZmcYTekoDf1NNNoygK-vOANvIIvrSpFNQ5RT6f_ixNPH2BS95JyvT8lpgm-yUEwjTnlMKhUajcVs6gjaueGPjNUok3oqBuMKN7sSyCTWAqmbielfWrj0BprvZ22bgjP5WzSaTbRoFHdau7_zMpDBuQA